# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `requestjs-rails` gem.
# Please instead update this file by running `bin/tapioca gem requestjs-rails`.


# source://requestjs-rails//lib/requestjs-rails.rb#1
module Requestjs; end

# source://requestjs-rails//lib/requestjs/engine.rb#2
class Requestjs::Engine < ::Rails::Engine
  class << self
    # source://activesupport/7.1.3.4/lib/active_support/callbacks.rb#70
    def __callbacks; end
  end
end

# source://requestjs-rails//lib/requestjs/version.rb#2
Requestjs::VERSION = T.let(T.unsafe(nil), String)
