// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ChatController from "./chat_controller"
application.register("chat", ChatController)

import ConversationController from "./conversation_controller"
application.register("conversation", ConversationController)

import LanguageController from "./language_controller"
application.register("language", LanguageController)
