# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module Minitest::Mock; end
module Respondable::MODEL; end
module Respondable::SYSTEM_PROMPT; end
module Respondable::TEMPERATURE; end
module Respondable::TOP_P; end
