# See here for list of installed packages under 'ubuntu-22.04'
# https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

name: 'Continuous Deployment'
on:
  push:
    branches: ['main']
jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
  deploy_to_heroku:
    needs: run_tests
    runs-on: 'ubuntu-22.04'
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v4'

      - name: 'Deploy to Heroku'
        run: |
          heroku git:remote -a amico
          git push heroku main
