# See here for list of installed packages under 'ubuntu-22.04'
# https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2204-Readme.md

name: "Continuous Deployment"
on:
  push:
    branches: ["main"]
jobs:
  run_tests:
    uses: ./.github/workflows/run_tests.yml
    secrets: inherit
  deploy_to_heroku:
    needs: run_tests
    runs-on: "ubuntu-22.04"
    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v4"

      - name: "Deploy to Heroku"
        uses: akhileshns/heroku-deploy@v3.13.15 # This is the action
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: "amico"
          heroku_email: "mail@tombarone.net"
